name: programmer
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  hidden_drawer_menu: ^3.0.1
  lottie: ^1.3.0
  animated_splash_screen: ^1.2.0
  syncfusion_flutter_datagrid: ^20.1.60

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  provider: ^6.0.0
  flutter_svg: ^1.1.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500
